//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.STUDENT_SECTIONS = new HashSet<STUDENT_SECTIONS>();
        }
    
        public long student_number { get; set; }
        public string student_name { get; set; }
        public double gpa { get; set; }
        public int department_id { get; set; }
        public int advisor_id { get; set; }
        public int id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual INSTRUCTOR INSTRUCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_SECTIONS> STUDENT_SECTIONS { get; set; }
    }
}
